spring.application.name=PizzariaDefault

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/PizzaDefault
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT:8080}